### ISSUE TITLE
venv

### ISSUE THREAD

**Issue by jholl** [AndrewCull/pelican-starter#1]
I think we need to .gitignore the venv directory and let developers create that locally ... I can get the project started

```
$ git clone https://....
$ cd project-dir
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r
```

when I try to `$ pip install -r` into the cloned `venv` directory I don't have permission, but if I create the `virtualenv venv` then I have no issue.

Once I'm tracking the repo, I will be able to stay update with the project doing:

```
$ git fetch ....
$ source venv/bin/activate
$ pip install -r
```

And any changed dependencies someone adds into requirements.txt will now be in my virtualenv also.

**Comment by AndrewCull** [comment]
Perfect
